// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Cg4zSxUYZ0oeQ6gQ8uTFqnRsBMm1mxo',
    appId: '1:745552863171:web:e3ba657964c641fada2776',
    messagingSenderId: '745552863171',
    projectId: 'basha-lagbe-fed43',
    authDomain: 'basha-lagbe-fed43.firebaseapp.com',
    storageBucket: 'basha-lagbe-fed43.firebasestorage.app',
    measurementId: 'G-7WD0G7TVRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9INHpBxdBgQd7SLNyI8rJglgN4EMn9cw',
    appId: '1:745552863171:android:fe273430bc68f224da2776',
    messagingSenderId: '745552863171',
    projectId: 'basha-lagbe-fed43',
    storageBucket: 'basha-lagbe-fed43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55Frc1Gn609Q-tzkHaeV5pzE2Kp3Yvek',
    appId: '1:745552863171:ios:583cec56939bc176da2776',
    messagingSenderId: '745552863171',
    projectId: 'basha-lagbe-fed43',
    storageBucket: 'basha-lagbe-fed43.firebasestorage.app',
    iosBundleId: 'com.example.bashaLagbe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55Frc1Gn609Q-tzkHaeV5pzE2Kp3Yvek',
    appId: '1:745552863171:ios:583cec56939bc176da2776',
    messagingSenderId: '745552863171',
    projectId: 'basha-lagbe-fed43',
    storageBucket: 'basha-lagbe-fed43.firebasestorage.app',
    iosBundleId: 'com.example.bashaLagbe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Cg4zSxUYZ0oeQ6gQ8uTFqnRsBMm1mxo',
    appId: '1:745552863171:web:519ae3394562fa7cda2776',
    messagingSenderId: '745552863171',
    projectId: 'basha-lagbe-fed43',
    authDomain: 'basha-lagbe-fed43.firebaseapp.com',
    storageBucket: 'basha-lagbe-fed43.firebasestorage.app',
    measurementId: 'G-XKZK5T0SMV',
  );

}